### ISSUE TITLE
Improve cold-start and package installation

### ISSUE THREAD

**Issue by bruecktech** [bruecktech/play-with-cdk#2]

**Comment by pgarbe** [comment]
Maybe it helps to check if a cached response is already available. Especially for the default snippet ...

**Comment by bruecktech** [comment]
I was now able to squeeze in everything to the lambda package using npm-prune. Cold start is quite awesome now :-)

**Comment by bruecktech** [comment]
Fixed by packaging all the modules into the lambda deployment package
